<?php
	header("Content-type:image/jpeg");
	extract($_GET);
	$temp=explode("/",$username);
	$f=file_get_contents("../data/".$temp[0]."-Auth.txt");
	$ftemp=explode(";",$f);
	$stack=array();
	foreach($ftemp as $existingfile){
		if($existingfile!=$temp[1])
			array_push($stack,$existingfile);
	}
	$join=implode(";",$stack);
	$file=fopen("../data/".$temp[0]."-Auth.txt","w");
	fwrite($file,$join);
	fclose($file);
	sleep(5);
	$im=imagecreate(1,1);
	imagecolorallocate($im,0,0,0);
	imagejpeg($im);
?>